/**
 * @xpaysh/discovery — pure-function generators for the real agent-readable
 * discovery surface (llms.txt, schema.org JSON-LD, robots.txt allowlist,
 * A2A agent-card, RFC 9728 oauth-protected-resource).
 *
 * Note: the UCP business profile (`/.well-known/ucp`) is generated by
 * `@xpaysh/ucp-schemas#generateUcpProfile()`, not this package.
 */

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

export declare const LLMS_TXT_PATH: '/llms.txt';
export declare const OAUTH_PROTECTED_RESOURCE_PATH: '/.well-known/oauth-protected-resource';
export declare const AGENT_CARD_PATH: '/.well-known/agent-card.json';
export declare const SCHEMA_ORG_CONTEXT: 'https://schema.org/';

/**
 * Canonical AI-crawler User-Agent strings drawn from each vendor's published
 * docs as of 2026-05-16.
 */
export declare const REAL_AI_USER_AGENTS: readonly string[];

// ---------------------------------------------------------------------------
// llms.txt
// ---------------------------------------------------------------------------

export interface LlmsTxtLink {
  title: string;
  url: string;
}

export interface LlmsTxtCategory {
  name: string;
  url: string;
}

export interface LlmsTxtCommerceProtocols {
  acp?: string;
  ucp?: string;
  ap2?: string;
  mcp?: string;
}

export interface LlmsTxtOptions {
  siteName: string;
  siteDescription?: string;
  /** Site root URL. Trailing slash recommended. */
  siteUrl: string;
  merchantSlug?: string;
  /** Default = `[{title:'Shop home', url:siteUrl+'shop/'}, {title:'Products sitemap', url:siteUrl+'sitemap_index.xml'}]`. */
  storeLinks?: LlmsTxtLink[];
  catalogFeedUrl?: string;
  commerceProtocols?: LlmsTxtCommerceProtocols;
  /** e.g. `'https://store.example/?xpay_cart={token}'`. */
  cartDeeplinkPattern?: string;
  topCategories?: LlmsTxtCategory[];
  /** Trailing paragraph for AI shopping agents. Has a sensible default. */
  agentSummary?: string;
}

/** Generate the Markdown body for `/llms.txt` per [llmstxt.org](https://llmstxt.org). */
export declare function generateLlmsTxt(opts: LlmsTxtOptions): string;

// ---------------------------------------------------------------------------
// schema.org JSON-LD
// ---------------------------------------------------------------------------

export interface AggregateRatingInput {
  ratingValue: number;
  reviewCount: number;
}

export interface ProductJsonLdOptions {
  url: string;
  name: string;
  sku?: string;
  description?: string;
  images?: string[];
  /** Numeric or stringified price. `null` means "not currently priced". */
  price?: string | number | null;
  priceCurrency: string;
  /** Default = true. */
  inStock?: boolean;
  /** Override the BuyAction target URL. Defaults to `url`. */
  buyActionTarget?: string;
  /** ISO date. Defaults to the current year's December 31 (UTC). */
  priceValidUntil?: string;
  aggregateRating?: AggregateRatingInput;
  /** Override the JSON-LD `@context`. Defaults to `'https://schema.org/'`. */
  context?: string;
}

export interface ProductJsonLdSlimOptions {
  url: string;
  sku: string;
  buyActionTarget: string;
  context?: string;
}

export interface ItemListEntry {
  name: string;
  sku?: string;
  url: string;
  image?: string;
  price?: string | number | null;
  priceCurrency: string;
  inStock?: boolean;
}

export interface ItemListJsonLdOptions {
  name?: string;
  items: ItemListEntry[];
}

/** Generate a full schema.org Product JSON-LD with Offer + BuyAction. */
export declare function generateProductJsonLd(opts: ProductJsonLdOptions): object;

/**
 * Generate a slim Product JSON-LD that ONLY contributes the BuyAction +
 * canonical URL. Use when another SEO plugin already emits a full Product
 * block.
 */
export declare function generateProductJsonLdSlim(opts: ProductJsonLdSlimOptions): object;

/** Generate a schema.org ItemList for shop archives / homepages. */
export declare function generateItemListJsonLd(opts: ItemListJsonLdOptions): object;

// ---------------------------------------------------------------------------
// robots.txt
// ---------------------------------------------------------------------------

export interface RobotsTxtBlockOptions {
  /** The existing robots.txt content; default `''`. */
  existingRobotsTxt?: string;
  /** UA list. Default = `REAL_AI_USER_AGENTS`. */
  agents?: readonly string[];
  /** Header line. Default = `'# xpay — shopping agents allowed'`. */
  header?: string;
}

export interface RobotsTxtBlockResult {
  robotsTxt: string;
  /** Agents whose Allow block was appended (i.e. not already mentioned). */
  appendedAgents: string[];
}

/**
 * Append Allow blocks for real AI crawlers not already mentioned. Mirrors the
 * WC plugin's behaviour — never overrides a UA the merchant has already
 * configured (Allow or Disallow).
 */
export declare function generateRobotsTxtBlock(opts?: RobotsTxtBlockOptions): RobotsTxtBlockResult;

// ---------------------------------------------------------------------------
// /.well-known/agent-card.json (A2A 1.0)
// ---------------------------------------------------------------------------

export interface AgentCardSkill {
  id: string;
  name: string;
  description?: string;
}

export interface AgentCardProvider {
  name: string;
  url: string;
}

export interface AgentCardOptions {
  name: string;
  description?: string;
  url: string;
  version: string;
  capabilities?: Record<string, boolean>;
  skills?: AgentCardSkill[];
  provider?: AgentCardProvider;
}

export declare const DEFAULT_AGENT_CARD_SKILLS: readonly AgentCardSkill[];
export declare const DEFAULT_AGENT_CARD_CAPABILITIES: Readonly<Record<string, boolean>>;

/** Generate the JSON body for `/.well-known/agent-card.json` per A2A 1.0. */
export declare function generateAgentCardJson(opts: AgentCardOptions): object;

// ---------------------------------------------------------------------------
// /.well-known/oauth-protected-resource (RFC 9728)
// ---------------------------------------------------------------------------

export interface OAuthProtectedResourceOptions {
  resource: string;
  resourceName?: string;
  authorizationServers: string[];
  scopesSupported?: string[];
  bearerMethodsSupported?: string[];
  resourceDocumentation?: string;
  resourceSigningAlgValuesSupported?: string[];
}

/** Generate the JSON body for `/.well-known/oauth-protected-resource` per RFC 9728. */
export declare function generateOAuthProtectedResource(opts: OAuthProtectedResourceOptions): object;

// ---------------------------------------------------------------------------
// Emitter descriptors
// ---------------------------------------------------------------------------

export interface EmitterDescriptor {
  /** The well-known path or URL path (no query string). */
  path: string;
  /** Content-Type header value. */
  contentType: string;
  /** Whether the emitter is enabled by default. */
  defaultOn: boolean;
  /** Canonical spec URL the emitter implements. */
  spec: string;
}

/**
 * Standard emitter descriptors. Sibling plugins import this map and wire each
 * descriptor into their platform-specific request router.
 *
 * UCP business profile is NOT in this map; it lives in `@xpaysh/ucp-schemas`.
 */
export declare const STANDARD_EMITTERS: Readonly<Record<'llms' | 'oauthProtectedResource' | 'agentCard', EmitterDescriptor>>;
